# Cleaning Out
Network.delete_all
Show.delete_all
amc = Network.create(name: "AMC")
nbc = Network.create(name: "NBC")
Show.create(name: "Mad Men", day_of_week: "Sunday", hour_of_day: 22, network: amc)
Show.create(name: "Community", day_of_week: "Thursday", hour_of_day: 20, network: nbc)
Show.create(name: "Breaking Bad", day_of_week: "Sunday", hour_of_day: 20, network: amc)
Show.create(name: "Modern Family", day_of_week: "Wednesday", hour_of_day: 19, network: nbc)

Recipe.delete_all

chicken_pie = Recipe.create(name: "Chicken Pie")
Ingredient.create(name: "Checken", recipe: chicken_pie)
Ingredient.create(name: "Carrot", recipe: chicken_pie)
Ingredient.create(name: "Onions", recipe: chicken_pie)
Ingredient.create(name: "Puff Pastry", recipe: chicken_pie)

paella = Recipe.create(name: "Paella")
Ingredient.create(name: "Aborio Rice", recipe: paella)
Ingredient.create(name: "Safron", recipe: paella)
Ingredient.create(name: "Chorizo", recipe: paella)
Ingredient.create(name: "Fish Stock", recipe: paella)
Ingredient.create(name: "Prawn", recipe: paella)
Ingredient.create(name: "Garlic", recipe: paella)
Ingredient.create(name: "Onion", recipe: paella)

ceviche = Recipe.create(name: "Ceviche")
Ingredient.create(name: "Prawns", recipe: ceviche)
Ingredient.create(name: "Limes", recipe: ceviche)
Ingredient.create(name: "Pineapple Juice", recipe: ceviche)
Ingredient.create(name: "White Wine Vinegar", recipe: ceviche)
Ingredient.create(name: "Cilantro", recipe: ceviche)
Ingredient.create(name: "Red Onion", recipe: ceviche)
Ingredient.create(name: "Garlic", recipe: ceviche)

lavender_brownies = Recipe.create(name: "Lavender Brownies")
Ingredient.create(name: "Sugar", recipe: lavender_brownies)
Ingredient.create(name: "Dried Lavender", recipe: lavender_brownies)
Ingredient.create(name: "Chocolate", recipe: lavender_brownies)
Ingredient.create(name: "Butter", recipe: lavender_brownies)
Ingredient.create(name: "Salt", recipe: lavender_brownies)
Ingredient.create(name: "Cinnamon", recipe: lavender_brownies)
Ingredient.create(name: "Vanilla", recipe: lavender_brownies)
Ingredient.create(name: "Eggs", recipe: lavender_brownies)
Ingredient.create(name: "Flour", recipe: lavender_brownies)
Ingredient.create(name: "Wallnuts", recipe: lavender_brownies)

pico_de_gallo = Recipe.create(name: "Picco De Gallo")
Ingredient.create(name: "Tomatoes", recipe: pico_de_gallo)
Ingredient.create(name: "Garlic", recipe: pico_de_gallo)
Ingredient.create(name: "Onion", recipe: pico_de_gallo)
Ingredient.create(name: "Cilantro", recipe: pico_de_gallo)
Ingredient.create(name: "Jalapenos", recipe: pico_de_gallo)
Ingredient.create(name: "Lime", recipe: pico_de_gallo)
